name: msml-604
channels:
  - defaults
dependencies:
  - ca-certificates=2023.01.10
  - libcxx=14.0.6
  - libffi=3.4.2
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.9.16
  - readline=8.2
  - setuptools=66.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
    - filelock==3.12.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - markupsafe==2.1.2
    - mpmath==1.3.0
    - networkx==3.1
    - numpy==1.24.3
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - sympy==1.11.1
    - threadpoolctl==3.1.0
    - torch==2.0.0
    - typing-extensions==4.5.0
